### ISSUE TITLE
[Command Error] - AT+TXDR

### ISSUE THREAD

**Issue by lanselambor** [MultiTechSystems/Dot-AT-Firmware-beta#1]
Firmware **v3.0.0** and **v3.1.0** don't support TXDR setting, see message shows below.
Have tried DR0~DR15, all failed.
```
AT+TXDR=DR0

TX data rate invalid

ERROR
```

**Comment by reissjason** [comment]
Which region were you using?
Did you test on mDot or xDot?
I had no issue with mDot US915 and AS923-JAPAN firmwares.

Did you try a reset of the config?  AT&F

**Comment by lanselambor** [comment]
Hi,

I'm using mDot US915. Have tried AT&F.

**Comment by reissjason** [comment]
What terminal program are you using to communicate via serial?

What is the result if you try just the number for a datarate
AT+TXDR=0

**Comment by lanselambor** [comment]
Hi, I'm using mDot US915 module, have tried AT&F. I have many mDot which were from three  manufacturing date, 2016, 2017(OK) and 2018(Got problem). 

Batch 2016 and 2017 use firmware:
```
ATI 

MultiTech mDot
Firmware: 2.0.16-mbed127
Library : 2.0.16-mbed127

OK
```

2018 uses firmware:
```
ATI

MultiTech mDot
Firmware : 3.0.0-mbed144
Library  : 3.0.0-mbed144
MTS-Lora : 3.0.0

OK
```

**Comment by lanselambor** [comment]
AT+TXRD=0

Command not found!

ERROR

**Comment by reissjason** [comment]
DOM on my device is April 2017
It works with v2.0.16, v3.0.0 and v3.1.0

**Comment by reissjason** [comment]
Can you try this command again?
AT+TXDR=0

**Comment by reissjason** [comment]
Does v2.0.16 work on the 2018 device?

**Comment by lanselambor** [comment]
**Yes, v2.0.16 work on the 2018 device.**

```
AT+TXDR=0

TX data rate invalid

ERROR


AT+TXDR=DR0

TX data rate invalid

ERROR
```

**Comment by lanselambor** [comment]
I tried to review the source code, but can find where this message from **TX data rate invalid**.

**Comment by reissjason** [comment]
Are you compiling your own firmware? Then yes a channel plan must be provided with v3.0.0 and v3.1.0.
This repo is pre-compiled firmware the channel plan is already included.
If you are having issues with the library this issue should be in libmDot-mbed5 or libmDot-dev-mbed5 project.

**Comment by lanselambor** [comment]
No, I'm not compiling the code, I just upload the firmware from the repo.

**Comment by lanselambor** [comment]
These are the three batch of modules I have, hope it can help trace what's the problem.

![img_4521](https://user-images.githubusercontent.com/9337688/42759112-6b8c2942-8938-11e8-8a53-06350741d915.jpg)

**Comment by lanselambor** [comment]
To correct the message I provide, just ignore the 868 version in the above picture. The problem is on 2018 US915 version, I got two brand new 2018-US915-version mDot, both of them not work with "AT+TXDR". What I want to do is to issue commands below, 

```
AT+NJM=3
AT+ACK=0
AT+NA=4D734662
AT+NSK=89ABC89ABC89ABC89ABC89ABC89ABC34
AT+DSK=45678904567890456789045678904567
AT+TXDR=DR3  (block here)
AT+TXP=11
AT+TXF=915300000
AT&W
ATZ
```

**Comment by reissjason** [comment]
With US915 in Peer-to-peer mode DR8-DR13 are the available datarates.
DR0-DR4 are used for Network Mode.

**Comment by lanselambor** [comment]
I tried DR0~DR15 all of them, please keep checking it.

**Comment by lanselambor** [comment]
Since the TXDR command has been changed after firmware v3.0.0, the document **[000643.pdf](https://www.multitech.com/documents/publications/manuals/s000643.pdf)** do not support this command anymore, refer to page 68,69. For page 69, **EU Data Rates Max Payload (bytes)** DR7 : 50, I think the number 50 is not as bytes, it's FSK: 50 kbps | 50000 bit/s, refer to [LoRaWAN-Regional-Parameters-v1.1rA.PDF](http://net868.ru/assets/pdf/LoRaWAN-Regional-Parameters-v1.1rA.PDF) page 9. 

![image](https://user-images.githubusercontent.com/9337688/42792021-fb56f13e-89a5-11e8-8410-1aba824c3f04.png)

And this is US915 TXDR description,

![image](https://user-images.githubusercontent.com/9337688/42792203-d17ed042-89a6-11e8-8a14-ed083414d219.png)

@reissjason Please review my sentences, if I say something wrong please figure it out. 🤝

**Comment by reissjason** [comment]
For FSK there was a software limitation causing a limit of 50 bytes. 
The limit in the v3.0.0 and v3.1.0 for FSK is 242.
Thanks for the feedback, we will update our documentation.
